name: bites
favicon: null
layout_spectrum: 0.99326
typography_spectrum: 1
title: Bespoke Bites
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#000000'
    - '#8f8f8f'
    - '#515151'
    - '#2e2e2e'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
